---
deployment:
  tasks:
    - /bin/cp -R /home/eldessdm/repositories/elderos-website/Home/. /home/eldessdm/public_html/
    - /bin/cp -R /home/eldessdm/repositories/elderos-website/Hiscores/. /home/eldessdm/hiscores.elderos.io/
    - /bin/cp -R /home/eldessdm/repositories/elderos-website/Play/. /home/eldessdm/play.elderos.io/
    - /bin/cp -R /home/eldessdm/repositories/elderos-website/Staff/. /home/eldessdm/staff.elderos.io/
    - /bin/cp -R /home/eldessdm/repositories/elderos-website/Vote/. /home/eldessdm/vote.elderos.io/
    - /bin/cp -R /home/eldessdm/repositories/elderos-website/shared/. /home/eldessdm/public_html/shared/
    - /bin/cp -R /home/eldessdm/repositories/elderos-website/shared/. /home/eldessdm/hiscores.elderos.io/shared/
    - /bin/cp -R /home/eldessdm/repositories/elderos-website/shared/. /home/eldessdm/play.elderos.io/shared/
    - /bin/cp -R /home/eldessdm/repositories/elderos-website/shared/. /home/eldessdm/vote.elderos.io/shared/
    - /bin/cp -R /home/eldessdm/repositories/elderos-website/shared/. /home/eldessdm/staff.elderos.io/shared/